version: "3.7"

# services:
#   redis-master:
#     image: kyhsa93/redis-master
#     restart: always

#   redis-slave:
#     image: kyhsa93/redis-slave
#     restart: always

database:
  image: mysql
  restart: always
  ports:
    - 3306:3306
  environment:
    - MYSQL_DATABASE=test
    - MYSQL_ROOT_PASSWORD=test
  command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  cap_add:
    - SYS_NICE
  volumes:
    - ./database/nest:/var/lib/mysql

# rabbitmq:
#   image: rabbitmq:alpine
#   restart: always
#   ports: 
#     - 5672:5672
#     - 15672:15672
#   environment: 
#     RABBITMQ_DEFAULT_USER: root
#     RABBITMQ_DEFAULT_PASS: test