  
version: "3.7"

services:
  redis-master:
    image: kyhsa93/redis-master
    restart: always

  redis-slave:
    image: kyhsa93/redis-slave
    restart: always

  database:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    environment: 
      - MYSQL_ROOT_PASSWORD=test

  rabbitmq:
    image: rabbitmq:alpine
    restart: always
    ports: 
      - 5672:5672
      - 15672:15672
    environment: 
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: andres16